export const GLOBANT_POSITIONS = [
  'Web UI Developer',
  'Cloud Engineer',
  'QC Analyst',
  'User Experience Designer',
  'Java Developer',
  'Data Engineer',
  'Tech Manager',
  'Test Automation Engineer',
  'DevOps Engineer',
  'Visual Designer',
  'Business Analyst',
  'Project Manager',
  'Service Design',
  'Tech Director',
  'Client Partner',
  'Delivery Manager',
]
